# File: /docker/Makefile
# Project: stats
# File Created: 04-09-2021 08:39:45
# Author: Clay Risser <email@clayrisser.com>
# -----
# Last Modified: 07-10-2021 17:40:12
# Modified By: Clay Risser
# -----
# Promanager (c) Copyright 2021

include ../mkpm.mk
ifneq (,$(MKPM))
-include $(MKPM)/gnu

export NAME := mkpm-docker
export VERSION := 0.0.1
export CONTEXT := context

-include ../main.mk

endif
